// Code generated by Kitex v0.16.1. DO NOT EDIT.

package seckillservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	seckill "seckill-system/kitex_gen/seckill"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"DoSeckill": kitex.NewMethodInfo(
		doSeckillHandler,
		newSeckillServiceDoSeckillArgs,
		newSeckillServiceDoSeckillResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	seckillServiceServiceInfo                = NewServiceInfo()
	seckillServiceServiceInfoForClient       = NewServiceInfoForClient()
	seckillServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return seckillServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return seckillServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return seckillServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SeckillService"
	handlerType := (*seckill.SeckillService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "seckill",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func doSeckillHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*seckill.SeckillServiceDoSeckillArgs)
	realResult := result.(*seckill.SeckillServiceDoSeckillResult)
	success, err := handler.(seckill.SeckillService).DoSeckill(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSeckillServiceDoSeckillArgs() interface{} {
	return seckill.NewSeckillServiceDoSeckillArgs()
}

func newSeckillServiceDoSeckillResult() interface{} {
	return seckill.NewSeckillServiceDoSeckillResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) DoSeckill(ctx context.Context, req *seckill.DoSeckillReq) (r *seckill.DoSeckillResp, err error) {
	var _args seckill.SeckillServiceDoSeckillArgs
	_args.Req = req
	var _result seckill.SeckillServiceDoSeckillResult
	if err = p.c.Call(ctx, "DoSeckill", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
