// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package seckill

import (
	"context"
	"fmt"
)

type DoSeckillReq struct {
	ActivityId int64  `thrift:"activity_id,1,required" frugal:"1,required,i64" json:"activity_id"`
	UserId     string `thrift:"user_id,2,required" frugal:"2,required,string" json:"user_id"`
}

func NewDoSeckillReq() *DoSeckillReq {
	return &DoSeckillReq{}
}

func (p *DoSeckillReq) InitDefault() {
}

func (p *DoSeckillReq) GetActivityId() (v int64) {
	return p.ActivityId
}

func (p *DoSeckillReq) GetUserId() (v string) {
	return p.UserId
}
func (p *DoSeckillReq) SetActivityId(val int64) {
	p.ActivityId = val
}
func (p *DoSeckillReq) SetUserId(val string) {
	p.UserId = val
}

func (p *DoSeckillReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DoSeckillReq(%+v)", *p)
}

var fieldIDToName_DoSeckillReq = map[int16]string{
	1: "activity_id",
	2: "user_id",
}

type DoSeckillResp struct {
	Code    int32   `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg     string  `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	OrderId *string `thrift:"order_id,3,optional" frugal:"3,optional,string" json:"order_id,omitempty"`
	Status  *string `thrift:"status,4,optional" frugal:"4,optional,string" json:"status,omitempty"`
}

func NewDoSeckillResp() *DoSeckillResp {
	return &DoSeckillResp{}
}

func (p *DoSeckillResp) InitDefault() {
}

func (p *DoSeckillResp) GetCode() (v int32) {
	return p.Code
}

func (p *DoSeckillResp) GetMsg() (v string) {
	return p.Msg
}

var DoSeckillResp_OrderId_DEFAULT string

func (p *DoSeckillResp) GetOrderId() (v string) {
	if !p.IsSetOrderId() {
		return DoSeckillResp_OrderId_DEFAULT
	}
	return *p.OrderId
}

var DoSeckillResp_Status_DEFAULT string

func (p *DoSeckillResp) GetStatus() (v string) {
	if !p.IsSetStatus() {
		return DoSeckillResp_Status_DEFAULT
	}
	return *p.Status
}
func (p *DoSeckillResp) SetCode(val int32) {
	p.Code = val
}
func (p *DoSeckillResp) SetMsg(val string) {
	p.Msg = val
}
func (p *DoSeckillResp) SetOrderId(val *string) {
	p.OrderId = val
}
func (p *DoSeckillResp) SetStatus(val *string) {
	p.Status = val
}

func (p *DoSeckillResp) IsSetOrderId() bool {
	return p.OrderId != nil
}

func (p *DoSeckillResp) IsSetStatus() bool {
	return p.Status != nil
}

func (p *DoSeckillResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DoSeckillResp(%+v)", *p)
}

var fieldIDToName_DoSeckillResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "order_id",
	4: "status",
}

type SeckillService interface {
	DoSeckill(ctx context.Context, req *DoSeckillReq) (r *DoSeckillResp, err error)
}

type SeckillServiceDoSeckillArgs struct {
	Req *DoSeckillReq `thrift:"req,1" frugal:"1,default,DoSeckillReq" json:"req"`
}

func NewSeckillServiceDoSeckillArgs() *SeckillServiceDoSeckillArgs {
	return &SeckillServiceDoSeckillArgs{}
}

func (p *SeckillServiceDoSeckillArgs) InitDefault() {
}

var SeckillServiceDoSeckillArgs_Req_DEFAULT *DoSeckillReq

func (p *SeckillServiceDoSeckillArgs) GetReq() (v *DoSeckillReq) {
	if !p.IsSetReq() {
		return SeckillServiceDoSeckillArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SeckillServiceDoSeckillArgs) SetReq(val *DoSeckillReq) {
	p.Req = val
}

func (p *SeckillServiceDoSeckillArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SeckillServiceDoSeckillArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SeckillServiceDoSeckillArgs(%+v)", *p)
}

var fieldIDToName_SeckillServiceDoSeckillArgs = map[int16]string{
	1: "req",
}

type SeckillServiceDoSeckillResult struct {
	Success *DoSeckillResp `thrift:"success,0,optional" frugal:"0,optional,DoSeckillResp" json:"success,omitempty"`
}

func NewSeckillServiceDoSeckillResult() *SeckillServiceDoSeckillResult {
	return &SeckillServiceDoSeckillResult{}
}

func (p *SeckillServiceDoSeckillResult) InitDefault() {
}

var SeckillServiceDoSeckillResult_Success_DEFAULT *DoSeckillResp

func (p *SeckillServiceDoSeckillResult) GetSuccess() (v *DoSeckillResp) {
	if !p.IsSetSuccess() {
		return SeckillServiceDoSeckillResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SeckillServiceDoSeckillResult) SetSuccess(x interface{}) {
	p.Success = x.(*DoSeckillResp)
}

func (p *SeckillServiceDoSeckillResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SeckillServiceDoSeckillResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SeckillServiceDoSeckillResult(%+v)", *p)
}

var fieldIDToName_SeckillServiceDoSeckillResult = map[int16]string{
	0: "success",
}
