// Code generated by Kitex v0.16.1. DO NOT EDIT.

package activityservice

import (
	activity "activity/kitex_gen/activity"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateActivity(ctx context.Context, req *activity.CreateActivityReq, callOptions ...callopt.Option) (r *activity.CreateActivityResp, err error)
	GetActivity(ctx context.Context, req *activity.GetActivityReq, callOptions ...callopt.Option) (r *activity.GetActivityResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kActivityServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kActivityServiceClient struct {
	*kClient
}

func (p *kActivityServiceClient) CreateActivity(ctx context.Context, req *activity.CreateActivityReq, callOptions ...callopt.Option) (r *activity.CreateActivityResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateActivity(ctx, req)
}

func (p *kActivityServiceClient) GetActivity(ctx context.Context, req *activity.GetActivityReq, callOptions ...callopt.Option) (r *activity.GetActivityResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetActivity(ctx, req)
}
