// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order

import (
	"context"
	"fmt"
)

type CreateOrderReq struct {
	ActivityId int64  `thrift:"activity_id,1,required" frugal:"1,required,i64" json:"activity_id"`
	UserId     string `thrift:"user_id,2,required" frugal:"2,required,string" json:"user_id"`
}

func NewCreateOrderReq() *CreateOrderReq {
	return &CreateOrderReq{}
}

func (p *CreateOrderReq) InitDefault() {
}

func (p *CreateOrderReq) GetActivityId() (v int64) {
	return p.ActivityId
}

func (p *CreateOrderReq) GetUserId() (v string) {
	return p.UserId
}
func (p *CreateOrderReq) SetActivityId(val int64) {
	p.ActivityId = val
}
func (p *CreateOrderReq) SetUserId(val string) {
	p.UserId = val
}

func (p *CreateOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderReq(%+v)", *p)
}

var fieldIDToName_CreateOrderReq = map[int16]string{
	1: "activity_id",
	2: "user_id",
}

type CreateOrderResp struct {
	Code    int32  `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg     string `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	OrderId *int64 `thrift:"order_id,3,optional" frugal:"3,optional,i64" json:"order_id,omitempty"`
}

func NewCreateOrderResp() *CreateOrderResp {
	return &CreateOrderResp{}
}

func (p *CreateOrderResp) InitDefault() {
}

func (p *CreateOrderResp) GetCode() (v int32) {
	return p.Code
}

func (p *CreateOrderResp) GetMsg() (v string) {
	return p.Msg
}

var CreateOrderResp_OrderId_DEFAULT int64

func (p *CreateOrderResp) GetOrderId() (v int64) {
	if !p.IsSetOrderId() {
		return CreateOrderResp_OrderId_DEFAULT
	}
	return *p.OrderId
}
func (p *CreateOrderResp) SetCode(val int32) {
	p.Code = val
}
func (p *CreateOrderResp) SetMsg(val string) {
	p.Msg = val
}
func (p *CreateOrderResp) SetOrderId(val *int64) {
	p.OrderId = val
}

func (p *CreateOrderResp) IsSetOrderId() bool {
	return p.OrderId != nil
}

func (p *CreateOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResp(%+v)", *p)
}

var fieldIDToName_CreateOrderResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "order_id",
}

type QueryOrderReq struct {
	OrderId    *int64  `thrift:"order_id,1,optional" frugal:"1,optional,i64" json:"order_id,omitempty"`
	ActivityId *int64  `thrift:"activity_id,2,optional" frugal:"2,optional,i64" json:"activity_id,omitempty"`
	UserId     *string `thrift:"user_id,3,optional" frugal:"3,optional,string" json:"user_id,omitempty"`
}

func NewQueryOrderReq() *QueryOrderReq {
	return &QueryOrderReq{}
}

func (p *QueryOrderReq) InitDefault() {
}

var QueryOrderReq_OrderId_DEFAULT int64

func (p *QueryOrderReq) GetOrderId() (v int64) {
	if !p.IsSetOrderId() {
		return QueryOrderReq_OrderId_DEFAULT
	}
	return *p.OrderId
}

var QueryOrderReq_ActivityId_DEFAULT int64

func (p *QueryOrderReq) GetActivityId() (v int64) {
	if !p.IsSetActivityId() {
		return QueryOrderReq_ActivityId_DEFAULT
	}
	return *p.ActivityId
}

var QueryOrderReq_UserId_DEFAULT string

func (p *QueryOrderReq) GetUserId() (v string) {
	if !p.IsSetUserId() {
		return QueryOrderReq_UserId_DEFAULT
	}
	return *p.UserId
}
func (p *QueryOrderReq) SetOrderId(val *int64) {
	p.OrderId = val
}
func (p *QueryOrderReq) SetActivityId(val *int64) {
	p.ActivityId = val
}
func (p *QueryOrderReq) SetUserId(val *string) {
	p.UserId = val
}

func (p *QueryOrderReq) IsSetOrderId() bool {
	return p.OrderId != nil
}

func (p *QueryOrderReq) IsSetActivityId() bool {
	return p.ActivityId != nil
}

func (p *QueryOrderReq) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *QueryOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryOrderReq(%+v)", *p)
}

var fieldIDToName_QueryOrderReq = map[int16]string{
	1: "order_id",
	2: "activity_id",
	3: "user_id",
}

type QueryOrderResp struct {
	Code int32  `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg  string `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	Data *Order `thrift:"data,3,optional" frugal:"3,optional,Order" json:"data,omitempty"`
}

func NewQueryOrderResp() *QueryOrderResp {
	return &QueryOrderResp{}
}

func (p *QueryOrderResp) InitDefault() {
}

func (p *QueryOrderResp) GetCode() (v int32) {
	return p.Code
}

func (p *QueryOrderResp) GetMsg() (v string) {
	return p.Msg
}

var QueryOrderResp_Data_DEFAULT *Order

func (p *QueryOrderResp) GetData() (v *Order) {
	if !p.IsSetData() {
		return QueryOrderResp_Data_DEFAULT
	}
	return p.Data
}
func (p *QueryOrderResp) SetCode(val int32) {
	p.Code = val
}
func (p *QueryOrderResp) SetMsg(val string) {
	p.Msg = val
}
func (p *QueryOrderResp) SetData(val *Order) {
	p.Data = val
}

func (p *QueryOrderResp) IsSetData() bool {
	return p.Data != nil
}

func (p *QueryOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryOrderResp(%+v)", *p)
}

var fieldIDToName_QueryOrderResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "data",
}

type Order struct {
	Id         int64  `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	ActivityId int64  `thrift:"activity_id,2,required" frugal:"2,required,i64" json:"activity_id"`
	UserId     string `thrift:"user_id,3,required" frugal:"3,required,string" json:"user_id"`
	Status     string `thrift:"status,4,required" frugal:"4,required,string" json:"status"`
	CreatedAt  string `thrift:"created_at,5,required" frugal:"5,required,string" json:"created_at"`
}

func NewOrder() *Order {
	return &Order{}
}

func (p *Order) InitDefault() {
}

func (p *Order) GetId() (v int64) {
	return p.Id
}

func (p *Order) GetActivityId() (v int64) {
	return p.ActivityId
}

func (p *Order) GetUserId() (v string) {
	return p.UserId
}

func (p *Order) GetStatus() (v string) {
	return p.Status
}

func (p *Order) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *Order) SetId(val int64) {
	p.Id = val
}
func (p *Order) SetActivityId(val int64) {
	p.ActivityId = val
}
func (p *Order) SetUserId(val string) {
	p.UserId = val
}
func (p *Order) SetStatus(val string) {
	p.Status = val
}
func (p *Order) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *Order) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Order(%+v)", *p)
}

var fieldIDToName_Order = map[int16]string{
	1: "id",
	2: "activity_id",
	3: "user_id",
	4: "status",
	5: "created_at",
}

type OrderService interface {
	CreateOrder(ctx context.Context, req *CreateOrderReq) (r *CreateOrderResp, err error)

	QueryOrder(ctx context.Context, req *QueryOrderReq) (r *QueryOrderResp, err error)
}

type OrderServiceCreateOrderArgs struct {
	Req *CreateOrderReq `thrift:"req,1" frugal:"1,default,CreateOrderReq" json:"req"`
}

func NewOrderServiceCreateOrderArgs() *OrderServiceCreateOrderArgs {
	return &OrderServiceCreateOrderArgs{}
}

func (p *OrderServiceCreateOrderArgs) InitDefault() {
}

var OrderServiceCreateOrderArgs_Req_DEFAULT *CreateOrderReq

func (p *OrderServiceCreateOrderArgs) GetReq() (v *CreateOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceCreateOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCreateOrderArgs) SetReq(val *CreateOrderReq) {
	p.Req = val
}

func (p *OrderServiceCreateOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceCreateOrderResult struct {
	Success *CreateOrderResp `thrift:"success,0,optional" frugal:"0,optional,CreateOrderResp" json:"success,omitempty"`
}

func NewOrderServiceCreateOrderResult() *OrderServiceCreateOrderResult {
	return &OrderServiceCreateOrderResult{}
}

func (p *OrderServiceCreateOrderResult) InitDefault() {
}

var OrderServiceCreateOrderResult_Success_DEFAULT *CreateOrderResp

func (p *OrderServiceCreateOrderResult) GetSuccess() (v *CreateOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceCreateOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateOrderResp)
}

func (p *OrderServiceCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceQueryOrderArgs struct {
	Req *QueryOrderReq `thrift:"req,1" frugal:"1,default,QueryOrderReq" json:"req"`
}

func NewOrderServiceQueryOrderArgs() *OrderServiceQueryOrderArgs {
	return &OrderServiceQueryOrderArgs{}
}

func (p *OrderServiceQueryOrderArgs) InitDefault() {
}

var OrderServiceQueryOrderArgs_Req_DEFAULT *QueryOrderReq

func (p *OrderServiceQueryOrderArgs) GetReq() (v *QueryOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceQueryOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceQueryOrderArgs) SetReq(val *QueryOrderReq) {
	p.Req = val
}

func (p *OrderServiceQueryOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceQueryOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceQueryOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceQueryOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceQueryOrderResult struct {
	Success *QueryOrderResp `thrift:"success,0,optional" frugal:"0,optional,QueryOrderResp" json:"success,omitempty"`
}

func NewOrderServiceQueryOrderResult() *OrderServiceQueryOrderResult {
	return &OrderServiceQueryOrderResult{}
}

func (p *OrderServiceQueryOrderResult) InitDefault() {
}

var OrderServiceQueryOrderResult_Success_DEFAULT *QueryOrderResp

func (p *OrderServiceQueryOrderResult) GetSuccess() (v *QueryOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceQueryOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceQueryOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*QueryOrderResp)
}

func (p *OrderServiceQueryOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceQueryOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceQueryOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceQueryOrderResult = map[int16]string{
	0: "success",
}
