// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package activity

import (
	"context"
	"fmt"
)

type CreateActivityReq struct {
	Name      string `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Stock     int32  `thrift:"stock,2,required" frugal:"2,required,i32" json:"stock"`
	StartTime string `thrift:"start_time,3,required" frugal:"3,required,string" json:"start_time"`
	EndTime   string `thrift:"end_time,4,required" frugal:"4,required,string" json:"end_time"`
}

func NewCreateActivityReq() *CreateActivityReq {
	return &CreateActivityReq{}
}

func (p *CreateActivityReq) InitDefault() {
}

func (p *CreateActivityReq) GetName() (v string) {
	return p.Name
}

func (p *CreateActivityReq) GetStock() (v int32) {
	return p.Stock
}

func (p *CreateActivityReq) GetStartTime() (v string) {
	return p.StartTime
}

func (p *CreateActivityReq) GetEndTime() (v string) {
	return p.EndTime
}
func (p *CreateActivityReq) SetName(val string) {
	p.Name = val
}
func (p *CreateActivityReq) SetStock(val int32) {
	p.Stock = val
}
func (p *CreateActivityReq) SetStartTime(val string) {
	p.StartTime = val
}
func (p *CreateActivityReq) SetEndTime(val string) {
	p.EndTime = val
}

func (p *CreateActivityReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateActivityReq(%+v)", *p)
}

var fieldIDToName_CreateActivityReq = map[int16]string{
	1: "name",
	2: "stock",
	3: "start_time",
	4: "end_time",
}

type CreateActivityResp struct {
	Code       int32  `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg        string `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	ActivityId *int64 `thrift:"activity_id,3,optional" frugal:"3,optional,i64" json:"activity_id,omitempty"`
}

func NewCreateActivityResp() *CreateActivityResp {
	return &CreateActivityResp{}
}

func (p *CreateActivityResp) InitDefault() {
}

func (p *CreateActivityResp) GetCode() (v int32) {
	return p.Code
}

func (p *CreateActivityResp) GetMsg() (v string) {
	return p.Msg
}

var CreateActivityResp_ActivityId_DEFAULT int64

func (p *CreateActivityResp) GetActivityId() (v int64) {
	if !p.IsSetActivityId() {
		return CreateActivityResp_ActivityId_DEFAULT
	}
	return *p.ActivityId
}
func (p *CreateActivityResp) SetCode(val int32) {
	p.Code = val
}
func (p *CreateActivityResp) SetMsg(val string) {
	p.Msg = val
}
func (p *CreateActivityResp) SetActivityId(val *int64) {
	p.ActivityId = val
}

func (p *CreateActivityResp) IsSetActivityId() bool {
	return p.ActivityId != nil
}

func (p *CreateActivityResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateActivityResp(%+v)", *p)
}

var fieldIDToName_CreateActivityResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "activity_id",
}

type GetActivityReq struct {
	ActivityId int64 `thrift:"activity_id,1,required" frugal:"1,required,i64" json:"activity_id"`
}

func NewGetActivityReq() *GetActivityReq {
	return &GetActivityReq{}
}

func (p *GetActivityReq) InitDefault() {
}

func (p *GetActivityReq) GetActivityId() (v int64) {
	return p.ActivityId
}
func (p *GetActivityReq) SetActivityId(val int64) {
	p.ActivityId = val
}

func (p *GetActivityReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetActivityReq(%+v)", *p)
}

var fieldIDToName_GetActivityReq = map[int16]string{
	1: "activity_id",
}

type GetActivityResp struct {
	Code int32     `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg  string    `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	Data *Activity `thrift:"data,3,optional" frugal:"3,optional,Activity" json:"data,omitempty"`
}

func NewGetActivityResp() *GetActivityResp {
	return &GetActivityResp{}
}

func (p *GetActivityResp) InitDefault() {
}

func (p *GetActivityResp) GetCode() (v int32) {
	return p.Code
}

func (p *GetActivityResp) GetMsg() (v string) {
	return p.Msg
}

var GetActivityResp_Data_DEFAULT *Activity

func (p *GetActivityResp) GetData() (v *Activity) {
	if !p.IsSetData() {
		return GetActivityResp_Data_DEFAULT
	}
	return p.Data
}
func (p *GetActivityResp) SetCode(val int32) {
	p.Code = val
}
func (p *GetActivityResp) SetMsg(val string) {
	p.Msg = val
}
func (p *GetActivityResp) SetData(val *Activity) {
	p.Data = val
}

func (p *GetActivityResp) IsSetData() bool {
	return p.Data != nil
}

func (p *GetActivityResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetActivityResp(%+v)", *p)
}

var fieldIDToName_GetActivityResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "data",
}

type Activity struct {
	Id          int64  `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Name        string `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Stock       int32  `thrift:"stock,3,required" frugal:"3,required,i32" json:"stock"`
	RemainStock int32  `thrift:"remain_stock,4,required" frugal:"4,required,i32" json:"remain_stock"`
	StartTime   string `thrift:"start_time,5,required" frugal:"5,required,string" json:"start_time"`
	EndTime     string `thrift:"end_time,6,required" frugal:"6,required,string" json:"end_time"`
	Status      int32  `thrift:"status,7,required" frugal:"7,required,i32" json:"status"`
}

func NewActivity() *Activity {
	return &Activity{}
}

func (p *Activity) InitDefault() {
}

func (p *Activity) GetId() (v int64) {
	return p.Id
}

func (p *Activity) GetName() (v string) {
	return p.Name
}

func (p *Activity) GetStock() (v int32) {
	return p.Stock
}

func (p *Activity) GetRemainStock() (v int32) {
	return p.RemainStock
}

func (p *Activity) GetStartTime() (v string) {
	return p.StartTime
}

func (p *Activity) GetEndTime() (v string) {
	return p.EndTime
}

func (p *Activity) GetStatus() (v int32) {
	return p.Status
}
func (p *Activity) SetId(val int64) {
	p.Id = val
}
func (p *Activity) SetName(val string) {
	p.Name = val
}
func (p *Activity) SetStock(val int32) {
	p.Stock = val
}
func (p *Activity) SetRemainStock(val int32) {
	p.RemainStock = val
}
func (p *Activity) SetStartTime(val string) {
	p.StartTime = val
}
func (p *Activity) SetEndTime(val string) {
	p.EndTime = val
}
func (p *Activity) SetStatus(val int32) {
	p.Status = val
}

func (p *Activity) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Activity(%+v)", *p)
}

var fieldIDToName_Activity = map[int16]string{
	1: "id",
	2: "name",
	3: "stock",
	4: "remain_stock",
	5: "start_time",
	6: "end_time",
	7: "status",
}

type ActivityService interface {
	CreateActivity(ctx context.Context, req *CreateActivityReq) (r *CreateActivityResp, err error)

	GetActivity(ctx context.Context, req *GetActivityReq) (r *GetActivityResp, err error)
}

type ActivityServiceCreateActivityArgs struct {
	Req *CreateActivityReq `thrift:"req,1" frugal:"1,default,CreateActivityReq" json:"req"`
}

func NewActivityServiceCreateActivityArgs() *ActivityServiceCreateActivityArgs {
	return &ActivityServiceCreateActivityArgs{}
}

func (p *ActivityServiceCreateActivityArgs) InitDefault() {
}

var ActivityServiceCreateActivityArgs_Req_DEFAULT *CreateActivityReq

func (p *ActivityServiceCreateActivityArgs) GetReq() (v *CreateActivityReq) {
	if !p.IsSetReq() {
		return ActivityServiceCreateActivityArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ActivityServiceCreateActivityArgs) SetReq(val *CreateActivityReq) {
	p.Req = val
}

func (p *ActivityServiceCreateActivityArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ActivityServiceCreateActivityArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ActivityServiceCreateActivityArgs(%+v)", *p)
}

var fieldIDToName_ActivityServiceCreateActivityArgs = map[int16]string{
	1: "req",
}

type ActivityServiceCreateActivityResult struct {
	Success *CreateActivityResp `thrift:"success,0,optional" frugal:"0,optional,CreateActivityResp" json:"success,omitempty"`
}

func NewActivityServiceCreateActivityResult() *ActivityServiceCreateActivityResult {
	return &ActivityServiceCreateActivityResult{}
}

func (p *ActivityServiceCreateActivityResult) InitDefault() {
}

var ActivityServiceCreateActivityResult_Success_DEFAULT *CreateActivityResp

func (p *ActivityServiceCreateActivityResult) GetSuccess() (v *CreateActivityResp) {
	if !p.IsSetSuccess() {
		return ActivityServiceCreateActivityResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ActivityServiceCreateActivityResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateActivityResp)
}

func (p *ActivityServiceCreateActivityResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ActivityServiceCreateActivityResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ActivityServiceCreateActivityResult(%+v)", *p)
}

var fieldIDToName_ActivityServiceCreateActivityResult = map[int16]string{
	0: "success",
}

type ActivityServiceGetActivityArgs struct {
	Req *GetActivityReq `thrift:"req,1" frugal:"1,default,GetActivityReq" json:"req"`
}

func NewActivityServiceGetActivityArgs() *ActivityServiceGetActivityArgs {
	return &ActivityServiceGetActivityArgs{}
}

func (p *ActivityServiceGetActivityArgs) InitDefault() {
}

var ActivityServiceGetActivityArgs_Req_DEFAULT *GetActivityReq

func (p *ActivityServiceGetActivityArgs) GetReq() (v *GetActivityReq) {
	if !p.IsSetReq() {
		return ActivityServiceGetActivityArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ActivityServiceGetActivityArgs) SetReq(val *GetActivityReq) {
	p.Req = val
}

func (p *ActivityServiceGetActivityArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ActivityServiceGetActivityArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ActivityServiceGetActivityArgs(%+v)", *p)
}

var fieldIDToName_ActivityServiceGetActivityArgs = map[int16]string{
	1: "req",
}

type ActivityServiceGetActivityResult struct {
	Success *GetActivityResp `thrift:"success,0,optional" frugal:"0,optional,GetActivityResp" json:"success,omitempty"`
}

func NewActivityServiceGetActivityResult() *ActivityServiceGetActivityResult {
	return &ActivityServiceGetActivityResult{}
}

func (p *ActivityServiceGetActivityResult) InitDefault() {
}

var ActivityServiceGetActivityResult_Success_DEFAULT *GetActivityResp

func (p *ActivityServiceGetActivityResult) GetSuccess() (v *GetActivityResp) {
	if !p.IsSetSuccess() {
		return ActivityServiceGetActivityResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ActivityServiceGetActivityResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetActivityResp)
}

func (p *ActivityServiceGetActivityResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ActivityServiceGetActivityResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ActivityServiceGetActivityResult(%+v)", *p)
}

var fieldIDToName_ActivityServiceGetActivityResult = map[int16]string{
	0: "success",
}
